name: Run Animate.ps1

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  run-animate:
    runs-on: windows-latest  # Use the appropriate runner (Windows, macOS, or Linux)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run animate.ps1
        shell: pwsh
        run: .\animate.ps1
